# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: NucleosProfileBundle
  description: 👤 Registration and profile management for symfony
  homepage: https://docs.nucleos.rocks/projects/profile-bundle/
  topics: hacktoberfest, symfony, symfony-bundle, bundle, user, management, profile, registration

branches:
  - name: "*.x"
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (8)"
          - "Static Code Analysis (8.1)"
          - "Test (PHP 8, symfony 5.4, lowest)"
          - "Test (PHP 8, symfony 5.4, highest)"
          - "Test (PHP 8.1, symfony 5.4, lowest)"
          - "Test (PHP 8.1, symfony 5.4, highest)"
          - "Code Coverage (8.1)"
          - "Mutation Tests (8.1)"
          - "Mutation Tests (8.1)"
        strict: true

      required_pull_request_reviews: null
      restrictions:
        users:
          - nucleos-bot
