_extends: .github

repository:
  name: NucleosProfileBundle
  description: 👤 Registration and profile management for symfony
  homepage: https://docs.nucleos.rocks/projects/profile-bundle/
  topics: hacktoberfest, symfony, symfony-bundle, bundle, user, management, profile, registration
