name: 'Documentation'

on:
  pull_request:
    paths:
      - 'docs/**'
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'
    tags:

jobs:
  run:
    uses: "nucleos/actions/.github/workflows/documentation.yml@main"

